import { useEffect, useState } from "react";
import { collection, doc, onSnapshot, query, updateDoc, where, getDoc } from "firebase/firestore";
import { db } from "../../lib/firebase";
import { useAuth } from "../../context/AuthContext";

export default function AdminExcuses() {
 const { adminTeamIds, adminSchoolIds, isSuperAdmin, user } = useAuth(); const [excuses,setExcuses]=useState([]); const [globalAdmin,setGlobalAdmin]=useState(false);
 useEffect(()=>{if(!user)return;return onSnapshot(doc(db,"settings","global"),s=>setGlobalAdmin(isSuperAdmin||(s.exists()&&(s.data().excuseAdminIds||[]).includes(user.uid))))},[user,isSuperAdmin]);
 useEffect(()=>{const un=[];let map={};const flush=()=>setExcuses(Object.values(map).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0))); const qs=[]; if(isSuperAdmin) qs.push(query(collection(db,"excuses"))); else {adminTeamIds.forEach(id=>qs.push(query(collection(db,"excuses"),where("teamId","==",id))));adminSchoolIds.forEach(id=>qs.push(query(collection(db,"excuses"),where("schoolId","==",id))));} qs.forEach(q=>un.push(onSnapshot(q,s=>{s.docs.forEach(d=>map[d.id]={id:d.id,...d.data()});flush();})));return()=>un.forEach(x=>x());},[isSuperAdmin,adminTeamIds.join(","),adminSchoolIds.join(",")]);
 if(!globalAdmin && !adminTeamIds.length && !adminSchoolIds.length) return <p className="text-sm font-body text-ink/40">لا يوجد لديك صلاحية لمشاهدة الاعتذارات.</p>;
 return <div className="space-y-3">{excuses.map(x=><div key={x.id} className="bg-white rounded-xl2 shadow-sm border border-teal-900/5 p-4"><div className="flex justify-between gap-3"><div><b className="font-body text-teal-900">{x.studentName}</b><p className="text-sm font-body mt-1">{x.meetingTitle}</p><p className="text-sm font-body text-ink/70 mt-2">سبب الاعتذار: {x.reason}</p></div><span className="text-xs font-body text-ink/40">{x.status==="new"?"جديد":x.status==="accepted"?"مقبول":"مرفوض"}</span></div>{x.status==="new"&&<div className="flex gap-2 mt-3"><button onClick={()=>updateDoc(doc(db,"excuses",x.id),{status:"accepted",adminReply:"تم قبول الاعتذار"})} className="bg-good text-white px-4 py-2 rounded-lg text-xs font-body font-semibold">قبول الاعتذار</button><button onClick={()=>updateDoc(doc(db,"excuses",x.id),{status:"rejected",adminReply:"تم رفض الاعتذار"})} className="bg-bad text-white px-4 py-2 rounded-lg text-xs font-body font-semibold">رفض الاعتذار</button></div>}</div>)}{!excuses.length&&<p className="text-sm font-body text-ink/40">لا توجد اعتذارات دلوقتي.</p>}</div>;
}
