import { useEffect, useMemo, useState } from "react";
import { addDoc, collection, doc, onSnapshot, query, where, setDoc, Timestamp } from "firebase/firestore";
import { ref, uploadBytes, getDownloadURL } from "firebase/storage";
import { db, storage } from "../lib/firebase";
import { useAuth } from "../context/AuthContext";
import { useLanguage } from "../context/LanguageContext";
import TopBar from "../components/TopBar";
import BirthdayNotifications from "../components/BirthdayNotifications";

const EVENT_CATALOG = ["مدرسة m power", "مدرسة impact", "مدرسة Scaleright", "مدرسة الأعضاء الجدد", "أولومبيات القادة", "قعدة رجالة"];
function monthsBetween(startDate,endDate){if(!startDate)return 0;const s=startDate.toDate?startDate.toDate():new Date(startDate);return Math.max((endDate.getFullYear()-s.getFullYear())*12+endDate.getMonth()-s.getMonth(),0)}

export default function StudentDashboard(){
 const {user,profile,teams}=useAuth(); const {t}=useLanguage();
 const [meetings,setMeetings]=useState([]),[attendance,setAttendance]=useState([]),[availability,setAvailability]=useState({}),[posts,setPosts]=useState([]),[postText,setPostText]=useState(""),[postImage,setPostImage]=useState(null),[posting,setPosting]=useState(false),[excuseOpen,setExcuseOpen]=useState(null),[excuseReason,setExcuseReason]=useState(""),[sendingExcuse,setSendingExcuse]=useState(false),[excuses,setExcuses]=useState([]);
 useEffect(()=>{if(!profile?.teamId)return;return onSnapshot(query(collection(db,"meetings"),where("date",">=",Timestamp.now())),snap=>setMeetings(snap.docs.map(d=>({id:d.id,...d.data()})).filter(m=>!m.teamId||m.teamId===profile.teamId).sort((a,b)=>(a.date?.toMillis?.()||0)-(b.date?.toMillis?.()||0))),e=>console.error(e))},[profile?.teamId]);
 useEffect(()=>{if(!user)return;return onSnapshot(query(collection(db,"attendanceRecords"),where("studentId","==",user.uid)),s=>setAttendance(s.docs.map(d=>d.data())))},[user]);
 useEffect(()=>{if(!user)return;return onSnapshot(query(collection(db,"availability"),where("studentId","==",user.uid)),s=>{const m={};s.docs.forEach(d=>m[d.data().eventId]=d.data().available);setAvailability(m)})},[user]);
 useEffect(()=>{if(!user)return;return onSnapshot(collection(db,"teamPosts"),s=>setPosts(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0))),e=>console.error("posts",e))},[user]);
 useEffect(()=>{if(!user)return;return onSnapshot(query(collection(db,"excuses"),where("studentId","==",user.uid)),s=>setExcuses(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0)))},[user]);
 const toggleAvailability=async id=>{try{const next=!availability[id];await setDoc(doc(db,"availability",`${id}_${user.uid}`),{eventId:id,studentId:user.uid,teamId:profile.teamId,schoolId:null,available:next,updatedAt:Timestamp.now()},{merge:true})}catch(err){alert("حصل خطأ ومقدرناش نأكد حضورك. تأكد إنك داخل بحسابك وجرب تاني.\n\n"+err.message)}};
 const publishPost=async e=>{e.preventDefault();if(!postText.trim()&&!postImage)return;setPosting(true);try{let imageUrl="";if(postImage){if(postImage.size>8*1024*1024)throw new Error("حجم الصورة أكبر من 8MB");const safe=postImage.name.replace(/[^a-zA-Z0-9._-]/g,"_");const r=ref(storage,`teamPosts/all/${user.uid}/${Date.now()}_${safe}`);await uploadBytes(r,postImage,{contentType:postImage.type});imageUrl=await getDownloadURL(r)}await addDoc(collection(db,"teamPosts"),{teamId:profile.teamId||null,teamName:profile.teamName||"",authorId:user.uid,authorName:profile.name||user.displayName||"عضو",authorPhoto:profile.photoURL||user.photoURL||"",text:postText.trim(),imageUrl,createdAt:Timestamp.now()});setPostText("");setPostImage(null);const f=document.getElementById("post-image-input");if(f)f.value=""}catch(err){console.error(err);alert("حصل خطأ ومقدرناش نبعت الرسالة/الصورة.\n\n"+err.message)}finally{setPosting(false)}};
 const sendExcuse=async()=>{if(!excuseOpen||!excuseReason.trim()||sendingExcuse)return;setSendingExcuse(true);try{await addDoc(collection(db,"excuses"),{meetingId:excuseOpen.id,meetingTitle:excuseOpen.title,meetingDate:excuseOpen.date,teamId:profile.teamId,schoolId:null,studentId:user.uid,studentName:profile.name,reason:excuseReason.trim(),status:"new",createdAt:Timestamp.now()});setExcuseOpen(null);setExcuseReason("")}catch(err){console.error(err);alert("حصل خطأ ومقدرناش نبعت الاعتذار.\n\n"+err.message)}finally{setSendingExcuse(false)}};
 const presentCount=attendance.filter(a=>a.present).length,absentCount=attendance.filter(a=>a.present===false).length; const monthsSinceJoin=useMemo(()=>monthsBetween(profile?.createdAt,new Date())||1,[profile?.createdAt]); const paidCount=profile?.paidMonths?.length||0; const remainingMonths=Math.max(monthsSinceJoin-paidCount,0); const teamData=teams.find(t=>t.id===profile?.teamId); const teamCash=teamData?.cashNumber||""; const meetingList=meetings.filter(m=>m.type!=="event"),eventList=meetings.filter(m=>m.type==="event");
 return <div className="min-h-screen bg-sand-50"><TopBar/><div className="max-w-5xl mx-auto px-4 py-6 space-y-6"><BirthdayNotifications/>
   <div className="bg-teal-900 text-sand-50 rounded-xl2 p-5 flex items-center gap-4">{profile?.photoURL&&<img src={profile.photoURL} className="w-14 h-14 rounded-full border-2 border-gold-500" alt=""/>}<div><p className="font-display font-bold text-lg">{profile?.name}</p><p className="font-body text-teal-100/70 text-sm">فريق {profile?.teamName} · منطقة {profile?.region}</p><div className="flex flex-wrap gap-2 mt-1"><span className="text-xs font-body px-2 py-0.5 rounded-full bg-gold-500/20 text-gold-400">{profile?.memberTypeLabel||profile?.memberType}</span><span className="text-xs font-body px-2 py-0.5 rounded-full bg-white/10">{profile?.birthDate||""}</span></div></div></div>
   <div className="grid grid-cols-2 md:grid-cols-4 gap-4"><StatCard label="الحضور" value={presentCount} tone="good"/><StatCard label="الغياب" value={absentCount} tone="bad"/><StatCard label="فريقي" value={profile?.teamName||"—"}/><StatCard label="النوع" value={profile?.gender==="male"?"ولد":"بنت"}/></div>
   <section className="card p-5"><h2 className="font-display font-bold text-teal-950 mb-3">التعهد</h2><div className="flex justify-between text-sm font-body mb-2"><span className="text-ink/60">شهور تم دفعها</span><span className="font-bold text-good">{paidCount}</span></div><div className="flex justify-between text-sm font-body"><span className="text-ink/60">باقي عليك</span><span className="font-bold text-bad">{remainingMonths} شهر</span></div>{teamCash&&<p className="mt-4 text-sm font-body bg-gold-500/10 rounded-xl p-3">كاش الفريق: <b dir="ltr">{teamCash}</b></p>}<div className="w-full bg-sand-100 rounded-full h-2 mt-4 overflow-hidden"><div className="bg-gold-500 h-2 rounded-full" style={{width:`${Math.min(100,(paidCount/monthsSinceJoin)*100)}%`}}/></div></section>
   <section className="card p-5"><h2 className="font-display font-bold text-teal-950 mb-4">اللقاءات</h2><MeetingList items={meetingList} availability={availability} onAvailability={toggleAvailability} onExcuse={setExcuseOpen}/></section>
   <section id="events" className="card p-5"><h2 className="font-display font-bold text-teal-950 mb-4">{t("events")}</h2><div className="grid grid-cols-2 md:grid-cols-3 gap-2 mb-5">{EVENT_CATALOG.map(x=><div key={x} className="bg-sand-50 rounded-xl p-3 text-sm font-body font-semibold text-teal-900">{x}</div>)}</div><MeetingList items={eventList} availability={availability} onAvailability={toggleAvailability} onExcuse={setExcuseOpen} event/></section>
   <section className="card p-5"><div className="mb-4"><h2 className="font-display font-bold text-teal-950">{t("group")}</h2><p className="text-xs font-body text-ink/50">كل عضو يقدر يبعت رسالة أو صورة، والكل يشوفها.</p></div><form onSubmit={publishPost} className="space-y-2 mb-5"><textarea value={postText} onChange={e=>setPostText(e.target.value)} rows={3} placeholder="اكتب رسالة..." className="field-input resize-none"/><div className="flex gap-2 items-center"><input id="post-image-input" type="file" accept="image/*" onChange={e=>setPostImage(e.target.files?.[0]||null)} className="text-xs font-body flex-1"/><button disabled={posting} className="bg-teal-900 text-sand-50 px-4 py-2 rounded-xl font-body font-semibold disabled:opacity-50">{posting?"جاري الإرسال...":"إرسال"}</button></div>{postImage&&<p className="text-xs text-ink/50">تم اختيار: {postImage.name}</p>}</form><div className="space-y-4">{posts.map(p=><article key={p.id} className="border-t border-ink/5 pt-4"><div className="flex items-center gap-2">{p.authorPhoto&&<img src={p.authorPhoto} className="w-8 h-8 rounded-full" alt=""/>}<p className="font-body font-bold text-teal-900">{p.authorName}</p></div>{p.text&&<p className="font-body text-ink/80 whitespace-pre-wrap mt-1 leading-7">{p.text}</p>}{p.imageUrl&&<img src={p.imageUrl} alt="" className="mt-3 max-h-72 w-full object-contain rounded-xl bg-sand-50"/>}<p className="text-[11px] text-ink/40 font-body mt-2">{p.createdAt?.toDate?.().toLocaleString("ar-EG")}</p></article>)}{!posts.length&&<p className="text-sm font-body text-ink/40">لسه مفيش رسائل.</p>}</div></section>
   <section className="card p-5"><h2 className="font-display font-bold text-teal-950 mb-2">اعتذاراتي</h2><div className="space-y-2">{excuses.map(x=><div key={x.id} className="bg-sand-50 rounded-xl p-3 text-sm font-body"><b>{x.meetingTitle}</b> — {x.reason}<span className="block text-xs text-ink/40 mt-1">{x.status==="new"?"في انتظار رد الأدمن":x.status==="accepted"?"✓ تم قبول الاعتذار":"تم رفض الاعتذار"}</span></div>)}</div></section>
 </div>{excuseOpen&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={()=>setExcuseOpen(null)}><div className="bg-white rounded-xl2 p-6 max-w-md w-full" onClick={e=>e.stopPropagation()}><h3 className="font-display font-bold text-teal-950">إرسال اعتذار</h3><p className="font-body text-sm text-ink/50 mt-1">{excuseOpen.title}</p><textarea value={excuseReason} onChange={e=>setExcuseReason(e.target.value)} rows={4} className="field-input mt-4" placeholder="اكتب سبب الاعتذار..."/><div className="flex gap-2 mt-4"><button disabled={sendingExcuse||!excuseReason.trim()} onClick={sendExcuse} className="flex-1 bg-teal-900 disabled:opacity-50 text-sand-50 py-2.5 rounded-xl font-body font-semibold">{sendingExcuse?"جاري الإرسال...":"إرسال"}</button><button onClick={()=>setExcuseOpen(null)} className="px-4 border rounded-xl font-body">إلغاء</button></div></div></div>}</div>
}
function MeetingList({items,availability,onAvailability,onExcuse,event=false}){if(!items.length)return <p className="text-sm font-body text-ink/40">مفيش {event?"أحداث":"لقاءات"} مجدولة دلوقتي</p>;return <ul className="space-y-3">{items.map(m=>{const available=!!availability[m.id];return <li key={m.id} className="border-b border-ink/5 pb-3 last:border-0"><div className="flex justify-between gap-3"><div><p className="font-body font-semibold">{m.title}</p><p className="text-xs text-ink/50 font-body">📍 {m.location||"المكان غير محدد"}</p>{m.notes&&<p className="text-xs text-ink/50 font-body">{m.notes}</p>}{m.attachmentURL&&<a href={m.attachmentURL} target="_blank" rel="noreferrer" className="text-xs text-teal-800 underline block mt-1">📎 {m.attachmentName||"الملف المرفق"}</a>}</div><span className="text-sm text-teal-800 font-body whitespace-nowrap">{m.date?.toDate?.().toLocaleString("ar-EG")}</span></div><div className="grid grid-cols-2 gap-2 mt-2"><button onClick={()=>onAvailability(m.id)} className={`py-2 rounded-lg text-sm font-body font-semibold ${available?"bg-good/10 text-good border border-good":"bg-sand-50 text-ink/60 border border-ink/10"}`}>{available?"✓ تم تأكيد الحضور":"فوت — أكد حضورك"}</button><button onClick={()=>onExcuse(m)} className="py-2 rounded-lg text-sm font-body font-semibold border border-bad/20 text-bad bg-bad/5">أعتذر</button></div></li>})}</ul>}
function StatCard({label,value,tone="neutral"}){const color=tone==="good"?"text-good":tone==="bad"?"text-bad":"text-teal-900";return <div className="bg-white rounded-xl2 shadow-sm border border-teal-900/5 p-4 text-center"><p className={`font-display font-extrabold text-2xl ${color}`}>{value}</p><p className="font-body text-ink/60 text-sm mt-1">{label}</p></div>}
